pyproject.toml
Update pyproject.toml to add `tensorboard` as a dependency of the `notebooks` target.
The tensorboard package is required for step 10 of `notebooks/patch_tsmixer_getting_started.ipynb` to run the following expression:
```
trainer = Trainer(
model=model,
args=train_args,
train_dataset=train_dataset,
eval_dataset=valid_dataset,
callbacks=[early_stopping_callback],
)
```
Otherwise the following exception is raised:
```
RuntimeError: TensorBoardCallback requires tensorboard to be installed. Either update your PyTorch version or install tensorboardX.
```
=> Fix #14, "requires tensorboard to be installed" RuntimeError

hacking/datasets_from_tsp.py, tests/toolkit/test_time_series_preprocessor.py, tests/toolkit/test_util.py, tsfm_public/toolkit/time_series_preprocessor.py, tsfm_public/toolkit/util.py
Functionality to make getting datasets for training and evaluation easier.
=> Get dataset

tests/toolkit/test_time_series_forecasting_pipeline.py, tsfm_public/toolkit/time_series_forecasting_pipeline.py, tsfm_public/toolkit/time_series_preprocessor.py
Improve inference performance in the forecasting pipeline. Allows passing `batch_size` argument during instantiation -- then during forecasting, batches of this size will be processed.
=> Inference performance

tests/toolkit/test_dataset.py, tsfm_public/toolkit/dataset.py
=> Striding for datasets

pyproject.toml, tests/toolkit/test_time_series_preprocessor.py, tsfm_public/toolkit/time_series_preprocessor.py
Update the TimeSeriesPreprocessor to deprecate `get_datasets` functionality.
Create new standalone function `get_datasets` which takes a TimeSeriesPreprocessor -- functionally equivalent to previous `get_datasets`.
Create new standalone function `prepare_data_splits` which splits the input dataframe according to the split config. This function is used by `get_datasets`.
Rationale:
In some cases, notably when using the time series forecasting pipeline, we need to split the dataframes in the same way as `get_datasets` but we do not require pytorch datasets.
Addresses discussion in: https://github.com/ibm-granite/granite-tsfm/issues/53
=> Refactor get_datasets functionality

tests/toolkit/test_time_series_preprocessor.py, tests/toolkit/test_util.py, tsfm_public/toolkit/time_series_preprocessor.py, tsfm_public/toolkit/util.py
Add support to create univariate torch datasets from multivariate inputs for the purpose of channel independent pretraining.
=> Univariate dataset support

tests/toolkit/test_time_series_preprocessor.py, tsfm_public/toolkit/time_series_preprocessor.py
- Updates the frequency token mapping to use supported pandas frequencies
- Add `use_frequency_token` in `get_datasets` to get a dataset with the frequency token
- Add test case to check for proper frequency token
=> Fixes for frequency token

pyproject.toml
Limit numpy < 2, to resolve some issues with transformers library.
=> Limit numpy version

pyproject.toml
Transformers has a dependency of `"urllib3<2.0.0",`.
This PR ensures we don't violate that requirement, while still satisfying: https://www.mend.io/vulnerability-database/CVE-2024-37891
=> Limit urllib3 <2

pyproject.toml, tests/models/tinytimemixer/test_modeling_tinytimemixer.py, tests/toolkit/test_dataset.py, tests/toolkit/test_time_series_forecasting_pipeline.py, tests/toolkit/test_time_series_preprocessor.py, tsfm_public/models/tinytimemixer/configuration_tinytimemixer.py, tsfm_public/models/tinytimemixer/modeling_tinytimemixer.py, tsfm_public/models/tinytimemixer/utils/ttm_utils.py, tsfm_public/toolkit/time_series_preprocessor.py
Improves handling of inferred frequencies.
Improves `get_frequency_token` to consider minor variations of tokens and timedelta strings.
=> Improve frequency handling

tsfm_public/__init__.py, tsfm_public/toolkit/__init__.py
Use similar import structure as done in HF
=> Better HF style imports

tsfm_public/toolkit/time_series_forecasting_pipeline.py
Minor changes to the forecasting pipeline:
- Do not set `num_workers` in the data loader
- Default pipeline behavior was to add any known ground truth data and adding a suffix to the prediction columns ("_prediction") -- added a new option to disable this. Pass "add_known_ground_truth=False". When False, the only columns produced are the predictions **without** the suffix added to the column name.
=> Pipeline enhancement

pyproject.toml
Handle issue with ` build_pipeline_init_args` which became available only after 4.38.0
=> bump transformers version

README.md, services/inference/README.md
Update readme files, correct typos.
=> Services fixes

.github/workflows/inference-services-test.yml, services/inference/pyproject.toml
This reverts commit 29cc2a8ab53bb955fd426c16873c86c9f6ea3d2b.
Await new release of core component first.
=> :Revert "extend to 3.12 for service runtime too"

tsfm_public/toolkit/util.py
Use an implementation of strtobool instead of importing from distutils.
Addresses https://github.com/ibm-granite/granite-tsfm/issues/118
=> Avoid distutils due to deprecation

notebooks/recipes/energy_demand_forecasting/demand_forecast_zeroshot_recipe_minimal.ipynb, tsfm_public/toolkit/visualization.py
As part of pm/#86, make changes to plot_predictions to support zero-shot plot:
- Accept context_df (history) and predictions_df
- Use channel param to pass target_column name
- Create one plot, corresponding to target_column series history + prediction
Prerequisite for final changes on the recipe PR:
https://github.com/ibm-granite-community/granite-timeseries-cookbook/pull/2
I tested this on ttm_tutorial.ipynb as well as demand_forecast_zeroshot_recipe_minimal.ipynb.
=> Update plot_predictions to plot history + prediction

services/inference/Makefile, services/inference/tsfminference/__init__.py, services/inference/tsfminference/default_config.yml, services/inference/tsfminference/inference.py, services/inference/tsfminference/main.py
This moves the `model_dir` out of the configuration file and sets it via the environment variable `TSFM_MODEL_DIR`
The behavior is as follows:
* TSFM_MODEL_DIR set to what runtime sees in the environment
* If the above is not set, TSFM_MODEL_DIR will be set to the HF_HOME env var;
* If HF_HOME is not set, then TSFM_MODEL_DIR will default to the system temp directory
* If the resulting TSFM_MODEL_DIR is not present, the runtime will not start (we raise an Exception).
=> Tsfm model dir

README.md, notebooks/hfdemo/tinytimemixer/README.md, notebooks/hfdemo/tinytimemixer/full_benchmarking/README.md, notebooks/hfdemo/tinytimemixer/ttm_m4_hourly.ipynb
Readme update with data download instructions
=> Data download instructions

services/inference/tests/test_inference_lib.py, services/inference/tests/test_inference_service.py, services/inference/tsfminference/hf_service_handler.py, services/inference/tsfminference/tsfm_config.py
Add is_finetuned to the tsfm_config.json to be used to indicate that a serialized model is fine-tuned
Improve error checks: 
- check that a preprocessor exists if the model is fine-tuned
- check that there is no future_data provided if it is not needed
- check that additional columns are provided only when the model can handle it
=> Improve inference error checks

notebooks/hfdemo/tinytimemixer/full_benchmarking/foundts_leaderboard/ttm-b1-512.sh, notebooks/hfdemo/tinytimemixer/full_benchmarking/research-use-r2.sh, notebooks/hfdemo/tinytimemixer/full_benchmarking/sample_notebooks/research_use/ttm-r2_freq_benchmarking_1024_96.ipynb, notebooks/hfdemo/tinytimemixer/full_benchmarking/sample_notebooks/research_use/ttm-r2_freq_benchmarking_1536_96.ipynb, notebooks/hfdemo/tinytimemixer/full_benchmarking/sample_notebooks/research_use/ttm-r2_freq_benchmarking_512_96.ipynb, notebooks/hfdemo/tinytimemixer/full_benchmarking/sample_notebooks/ttm-r1_benchmarking_1024_96.ipynb, notebooks/hfdemo/tinytimemixer/full_benchmarking/sample_notebooks/ttm-r1_benchmarking_512_96.ipynb, notebooks/hfdemo/tinytimemixer/full_benchmarking/sample_notebooks/ttm-r2_benchmarking_1024_96.ipynb, notebooks/hfdemo/tinytimemixer/full_benchmarking/sample_notebooks/ttm-r2_benchmarking_512_96.ipynb, notebooks/hfdemo/tinytimemixer/full_benchmarking/ttm_full_benchmarking.py, notebooks/hfdemo/ttm_getting_started.ipynb, services/finetuning/Makefile, services/inference/Makefile, tests/toolkit/test_get_model.py, tsfm_public/resources/model_paths_config/ttm.yaml, tsfm_public/toolkit/get_model.py
- Update location of the repo containing models for testing services
- Update ibm/ttm-research-r2 to ibm-research/ttm-research-r2
=> Update model paths

tests/toolkit/test_time_series_preprocessor.py, tsfm_public/toolkit/time_series_preprocessor.py
Allows passing [] in scaling_id_columns. The options for training separate scalers are the following:
Assumptions: a dataset with the available id columns `["id_1", "id_2", "id_3]`
1) If `id_columns = ["id_1", "id_2"]`, `scaling_id_columns = None`: divide data into groups determined by the unique combinations of `["id_1", "id_2"]` and train separate scalers on each group.
2) If `id_columns = ["id_1", "id_2", "id_3"]`, `scaling_id_columns =["id_3"]`: divide data into groups determined by the unique combinations of `["id_3"]` and train separate scalers on each group.
3) If `id_columns = ["id_1", "id_2", "id_3"]`, `scaling_id_columns =[]`: treat data as a single group, only one scaler is trained.
4) If `id_columns = ["id_1", "id_2"]`, `scaling_id_columns =["id_3"]`: error. The …
=> support [] as scaling id columns

services/boilerplate/tsfm_config.py, services/boilerplate/tsfm_util.py, services/inference/tests/test_inference_service.py, services/inference/tsfminference/tsfm_inference_handler.py, tsfm_public/__init__.py, tsfm_public/toolkit/dataset.py, tsfm_public/toolkit/hf_util.py, tsfm_public/toolkit/time_series_forecasting_pipeline.py, tsfm_public/toolkit/util.py
Handle case when `tsfm_config.json` (services handler config) is missing.
Assumptions:
- If no config is provided, the model architecture code is available in either transformers or tsfm_public
- The order in which those libraries are checked is 1) transformers and then 2) tsfm_public. If you have a custom library that provides an inference handler for your custom model, the assumption is that you will provide a `tsfm_config.json`
- When no `tsfm_config.json` is provided, the default handler will be used.
To enable the above, we need to pre-register the config for models in `tsfm_public` (whose implementation is available there).
**work in progress**
=> Service missing config + support quality

services/inference/tests/test_inference_service.py
- User tsfm_public encode function.
- Add test with no tsfm_config.json. This is not recommended, since it currently limits our ability to properly valid inputs and format inputs, and may lead to unexpected results.
=> Minor updates to service tests

.github/workflows/python-package.yml
Potential fix for [https://github.com/ibm-granite/granite-tsfm/security/code-scanning/5](https://github.com/ibm-granite/granite-tsfm/security/code-scanning/5)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will specify the minimal permissions required for the workflow to function. Since the workflow only needs to read repository contents (e.g., to install dependencies and run tests), we will set `contents: read`. This ensures that the `GITHUB_TOKEN` has the least privilege necessary.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 5: Workflow does not contain permissions

services/finetuning/Makefile, tsfm_public/toolkit/lr_finder.py
Use of relative path "temp" creates issues with service image that doesn't necessarily have write access to PWD. It also accumulates files in local directories instead of auto-cleaned temporary directory
=> remove hardcoded relative path in lr_finder.py

.github/workflows/finetuning-service-test.yml
Potential fix for [https://github.com/ibm-granite/granite-tsfm/security/code-scanning/1](https://github.com/ibm-granite/granite-tsfm/security/code-scanning/1)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will explicitly define the permissions required for the workflow. Based on the provided workflow, it appears that the workflow only needs to read the repository contents and does not require any write permissions. Therefore, we will set `contents: read` as the minimal permissions.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 1: Workflow does not contain permissions

notebooks/tutorial/ttm_channel_mix_finetuning.ipynb
In commit 6ca6017 the project was renamed from `tsfm_public` to `granite-tsfm` in `pyproject.toml`.  
However, the mix channels finetuning tutorial notebook still referenced the old package name `tsfm_public` in the installation command, which caused pip errors such as:
`ERROR: Could not find a version that satisfies the requirement tsfm-public (unavailable) (from versions: none)
ERROR: No matching distribution found for tsfm-public (unavailable)`
- Updated the pip install command to use the correct package name:
```bash
pip install "granite-tsfm[notebooks] @ git+https://github.com/ibm-granite/granite-tsfm.git"
=> Fix outdated install command in finetuning notebook (renamed to granite-tsfm in 6ca6017)
