ibm-granite/granite-tsfm

- notebooks/hfdemo/patch_tst_getting_started.ipynb
- tsfm_public/toolkit/dataset.py
- tsfm_public/toolkit/time_series_preprocessor.py
Adds patchtst getting started notebook.
Dataset for regression tasks.
> Patchtst getting started

- tests/toolkit/conftest.py
- tests/toolkit/test_time_series_preprocessor.py
- tsfm_public/toolkit/time_series_forecasting_pipeline.py
- tsfm_public/toolkit/time_series_preprocessor.py
- tsfm_public/toolkit/util.py
Allow different ID columns for scaling.
> Scaling updates

- tests/toolkit/test_dataset.py
- tsfm_public/toolkit/dataset.py
Add observed mask creation to torch datasets.
> Observed mask

- pyproject.toml
Attempt to pin urllib3 to address https://www.mend.io/vulnerability-database/CVE-2024-37891
> address https://www.mend.io/vulnerability-database/CVE-2024-37891

- tsfm_public/models/__init__.py
Import individual models at the tsfm/models level. This is to make importing of models easier, especially when multiple models exist under tsfm/models.
> Adjust imports

- tests/toolkit/test_time_series_forecasting_pipeline.py
- tsfm_public/toolkit/time_series_forecasting_pipeline.py
Enable proper handling of the frequency token when using the time series forecasting pipeline.
Add some tests which use this functionality.
> Freq token with pipeline

- .github/workflows/inference-services-test.yml
- .github/workflows/python-package.yml
- pyproject.toml
- services/inference/pyproject.toml
Attempts to loosen range of supported python environments to include python 3.12
> attempt python 3.12 support

- services/inference/.gitignore
- services/inference/poetry.lock
- services/inference/pyproject.toml
- services/inference/tsfminference/.gitignore
- services/inference/tsfminference/__init__.py
- services/inference/tsfminference/_version.py
- services/inference/tsfminference/version.py
* first cut at introducing dynamic versioning
* tries to keep versioning scheme in sync with tsfm_public by using same git repo tag
> Services dynamic versioning

- tsfm_public/models/tinytimemixer/modeling_tinytimemixer.py
See: https://github.com/pytorch/pytorch/issues/133100
> address issue with clamp_min on MPS

- notebooks/hfdemo/tinytimemixer/ttm_benchmarking_1024_96.ipynb
- notebooks/hfdemo/tinytimemixer/ttm_benchmarking_512_96.ipynb
- notebooks/hfdemo/ttm_getting_started.ipynb
- tsfm_public/__init__.py
- tsfm_public/toolkit/__init__.py
Do not import plotting utilities, since their dependencies are optional.
> Some fixes for imports

- services/inference/tests/test_inference.py
- tests/toolkit/test_time_series_forecasting_pipeline.py
> Redirect to tests to "test-specific" models

- tests/toolkit/test_time_series_forecasting_pipeline.py
- tsfm_public/toolkit/time_series_forecasting_pipeline.py
Move defaults to init, per HF pipeline docs
Add a few tests
Check the length of the future time series data, and issue a warning if too much/not enough data is provided
> Update forecasting pipeline

- .github/workflows/inference-services-test.yml
- services/inference/README.md
Add more details about testing and setup.
> Doc improvements

- tests/toolkit/test_dataset.py
- tsfm_public/toolkit/dataset.py
- tsfm_public/toolkit/visualization.py
Addresses a few minor issues:
- set the number of plots appropriately in `plot_predictions`
- watch out for coercion of datetimes
- add a test for datetimes with utc
> Minor fixes

- tsfm_public/toolkit/visualization.py
Improve docstrings for `plot_predictions`
Fix issues with the forecast boundary line
> Plot fixes

- tsfm_public/toolkit/visualization.py
Update plotting to handle exogenous values when passing model and torch dataset.
Fixes issue https://github.com/ibm-granite/granite-tsfm/issues/134
> Handle exogenous during plotting

- tsfm_public/toolkit/util.py
Add some additional frequency strings to the list supported in tsf conversion.
Improve handling of the frequency strings.
> Better frequency handling for tsf format conversion

- services/boilerplate/errors.py
- services/boilerplate/hfutil.py
- services/inference/tests/test_inference.py
- services/inference/tsfminference/inference.py
> Wxai issue 42192 42193

- tsfm_public/toolkit/dataset.py
give more information about what column specifier is incorrect
> improved error messages for incorrect inputs

- tests/toolkit/test_dataset.py
- tsfm_public/toolkit/dataset.py
Allow more flexibility with masking specification
> Masking specification

- .github/workflows/inference-services-test.yml
- services/inference/tests/test_inference.py
- Clone the test model repo during git action
- Parameterize test to run on all models
> Add more tests for new model revisions

- services/inference/Makefile
- services/inference/tests/test_inference.py
- Remove TSFM_MODEL_DIR from some Make targets
- Update model dir in test cases
> Simplify path handling

- services/inference/tsfminference/inference.py
- tests/toolkit/test_dataset.py
- tests/toolkit/test_time_series_preprocessor.py
- tsfm_public/toolkit/dataset.py
- tsfm_public/toolkit/time_series_preprocessor.py
- Expose padding option
- Better checks with estimating frequency
- Sort inference input data for service
- Test cases
> Dataset fixes

- tsfm_public/toolkit/dataset.py
- tsfm_public/toolkit/time_series_forecasting_pipeline.py
- tsfm_public/toolkit/util.py
Starting with numpy 2.0, np.NaN no longer works
> Fix deprecated np.NaN

- tsfm_public/toolkit/dataset.py
Address: https://github.com/ibm-granite/granite-tsfm/issues/181
> check bounds on inner datasets

- tests/toolkit/test_time_series_preprocessor.py
- tsfm_public/toolkit/data_handling.py
- tsfm_public/toolkit/time_series_preprocessor.py
- tsfm_public/toolkit/util.py
Adds uniform random sampling of (context length + prediction length) windows from the train dataset returned by get_datasets.
> Window sampling

- .vscode/launch.json
- services/boilerplate/dataframe_checks.py
- services/inference/Makefile
- services/inference/poetry.lock
- services/inference/pyproject.toml
- services/inference/tests/test_inference.py
- services/inference/tsfminference/inference.py
- services/inference/tsfminference/main.py
* adds Prometheus /metrics endpoint
* instruments forecast method with cpu_user and wall clock histograms
* adds basic dataframe consistency checks against given payload schema
> Prometheus

- tsfm_public/toolkit/time_series_forecasting_pipeline.py
- tsfm_public/toolkit/time_series_preprocessor.py
Pull in some critical fixes for toolkit methods/functions.
> Toolkit fixes

- tsfm_public/toolkit/callbacks.py
- enable passing verbose during init of the TrackingCallback
> Updates to callbacks

- .whitesource
* also serves as a test to see if github workflow starts on upstream
> Remove .whitesource

- services/boilerplate/inference_payloads.py
Addresses: https://github.com/ibm-granite/granite-tsfm/issues/204
> relax parameters strictness

- wiki.md
Add comment about source of citations. Addresses: https://github.com/ibm-granite/granite-tsfm/issues/129
> clarify citations

- tsfm_public/toolkit/time_series_forecasting_pipeline.py
- Fixes issue with added future exogenous when a preprocessor is present
- Fixes issues with competing options (`add_known_ground_truth` and `explode_forecasts`)
> Address some issues in forecasting pipeline

- pyproject.toml
- tsfm_public/toolkit/time_series_forecasting_pipeline.py
Minor update for pypi release.
> New release

- tests/toolkit/test_time_series_preprocessor.py
- tsfm_public/toolkit/time_series_preprocessor.py
- wiki.md
- Fix link in wiki page
- Fix error checking with `categorical_columns`
- Fix frequency token mapping
- Add an additional check for `categorical_columns`
> Misc. fixes

- pyproject.toml
Try out newer numpy.
Addresses Issue #282
> try to bump numpy

- .github/workflows/finetuning-service-test.yml
- .github/workflows/inference-services-test.yml
- .github/workflows/python-package.yml
- services/inference/tsfminference/inference.py
another round of conflict resolution
> Destiny conflict resolve

- services/inference/tests/test_inference_lib.py
- services/inference/tests/test_inference_service.py
obtain tests on destiny_v1_patches
> V1 patches 2 destiny

- services/boilerplate/inference_payloads.py
- services/inference/tests/test_inference_service.py
- services/inference/tsfminference/tsfm_inference_handler.py
Updates to enable simpler inference requests when working in a BYOM setting.
> Schema checks

- .github/workflows/inactive-issues.yml
Adds an action to mark issues as stale and eventually close them if there is no response.
> add action for inactive issues

- services/inference/Dockerfile.cpu
- services/inference/Makefile
- tsfm_public/toolkit/time_series_preprocessor.py
> Destiny patches

- tests/toolkit/test_dataset.py
- tsfm_public/toolkit/dataset.py
Bring imputation/interpolation to main.
> Tsfm impute interpolate

- tsfm_public/toolkit/conformal.py
Hi, this PR includes the following updates:
* Added Enum classes and type hints.
* Updated some input parameters.
* Reordered arguments in methods requiring predictions and ground truth  (ground truth now comes first to align with sklearn conventions.)
Tested the PostHocProbabilisticProcessor on the bike forecasting notebook and it runs correctly.
> Conformal Enums and type hints update.

- .github/workflows/python-package.yml
* fixes incorrect 0% coverage report
* place a lower threshold on coverage amount for passing tests
> fix coverage report, impose lower bound using current coverage level

- tsfm_public/toolkit/time_series_preprocessor.py
Quick fix to address prediction_length==0
> Update error check on prediction length

- tests/toolkit/test_time_series_forecasting_pipeline.py
Confirm behavior for https://github.com/ibm-granite/granite-tsfm/issues/341
> add a test for prediction filter length

- tests/toolkit/test_conformal.py
- tsfm_public/toolkit/conformal.py
*  The update method is now included in the post-hoc probabilistic processor for adaptive conformal and gaussian approaches (https://github.com/ibm-granite/granite-tsfm/blob/a57deeaf80534462a99452de92d9813a9e922161/tsfm_public/toolkit/conformal.py#L298). 
* A test function to evaluate the update method was included (https://github.com/ibm-granite/granite-tsfm/blob/a57deeaf80534462a99452de92d9813a9e922161/tests/toolkit/test_conformal.py#L140).
> Update Method Enabled

- tests/models/tspulse/test_modeling_tspulse.py
- tsfm_public/toolkit/dataset.py
- tsfm_public/toolkit/time_series_anomaly_detection_pipeline.py
Initial changes to support preprocessor / feature extractor
> Changes to enable TTM in AD Pipeline

- tsfm_public/toolkit/time_series_preprocessor.py
Adds a check to ensure scaling factors can be learned.
Addresses https://github.com/ibm-granite/granite-tsfm/issues/376
> Address issue_376

- .github/workflows/python-package.yml
- README.md
- services/inference/poetry.lock
- services/inference/pyproject.toml
* reference main in poetry dependency
> reference main

- tests/toolkit/test_time_series_preprocessor.py
- tsfm_public/toolkit/time_series_preprocessor.py
Add power scaler capability to the preprocessor
> Power Scaler
